title: >-
  GLM configuration: Process-guided deep learning predictions of lake water temperature
cross-cites:
  -
    authors: ['Matthey R. Hipsey','Louise C. Bruce', 'David P. Hamilton']
    title: >-
      GLM General Lake Model: Model Overview and User Information
    pubdate: 2013
    link: http://aed.see.uwa.edu.au/research/models/GLM/index.html


attributes:
  -
    attr-label: glm_setup
    attr-def: parameters for setting up the General Lake Model and defining constants
    attr-defs: Hipsey et al. 2013
    data-min: NA
    data-max: NA
    data-units: NA
  -
    attr-label: morphometry
    attr-def: parameters describing the depth/area relationship of the lake for the General Lake Model
    attr-defs: Hipsey et al. 2013
    data-min: NA
    data-max: NA
    data-units: NA
  -
    attr-label: time
    attr-def: parameters describing the time period and frequency of model runs for the General Lake Model
    attr-defs: Hipsey et al. 2013
    data-min: NA
    data-max: NA
    data-units: NA
  -
    attr-label: output
    attr-def: parameters describing how the outputs of model runs from the General Lake Model are written
    attr-defs: Hipsey et al. 2013
    data-min: NA
    data-max: NA
    data-units: NA
  -
    attr-label: init_profiles
    attr-def: parameters describing General Lake Model initial conditions
    attr-defs: Hipsey et al. 2013
    data-min: NA
    data-max: NA
    data-units: NA
  -
    attr-label: meteorology
    attr-def: parameters describing time series drivers of General Lake Model runs
    attr-defs: Hipsey et al. 2013
    data-min: NA
    data-max: NA
    data-units: NA
  -
    attr-label: bird_model
    attr-def: parameters describing the use (if applicable) of the Bird model for General Lake Model runs
    attr-defs: Hipsey et al. 2013
    data-min: NA
    data-max: NA
    data-units: NA
  -
    attr-label: inflow
    attr-def: parameters describing inflows to the General Lake Model
    attr-defs: Hipsey et al. 2013
    data-min: NA
    data-max: NA
    data-units: NA
  -
    attr-label: outflow
    attr-def: parameters describing outflows from the General Lake Model
    attr-defs: Hipsey et al. 2013
    data-min: NA
    data-max: NA
    data-units: NA
  -
    attr-label: snowice
    attr-def: parameters describing how snow and ice dynamics are calculated by the General Lake Model
    attr-defs: Hipsey et al. 2013
    data-min: NA
    data-max: NA
    data-units: NA

build-environment: Multiple computer systems were used to generate these data, including linux, OSX. The open source language R was used on all systems, as well as the open-source model GLM.

process-date: 20160624
indirect-spatial: U.S.A.
latitude-res: 0.1
longitude-res: 0.1
data-name: Model configuration details
data-description: >-
  Model configurations for running the General Lake Model (Hipsey et al. 2013) for each lake, for each driver type. There are seven files that share identical formatting.
  Six files correspond to downscaled Global Circulation Models (Notaro et al. 2016), and one (NLDAS) are results from contemporary (1979-2015) meterology.
  Each file contains the same attributes (described above). NLDAS drivers (NLDAS_model_config.json) are described in
  Mitchell et al. 2004. The remaining six files are driven with models described in Notaro et al. 2015. The value for "lake_name" in the "morphometry"
  field is the mapping for "site_id" for the other datasets included in this release.
file-format: JSON (JavaScript Object Notation) formatted text files
